### ISSUE TITLE
Flight Enchantment

### ISSUE THREAD

**Issue by DarkerEnergon** [MSWS/FreakyEnchants#2]
**Name: GalaxyWing**
_Please try to be creative_

**Enchant Levels: 1-3**
_What would each level effect?_ : No need for a level system just let the enchant allow flight when ever worn or held.

**What items can this enchantment be applied to?**
- [ ] Swords
- [ ] Bows
- [x] Armor 
- [ ] Pickaxes 
- [ ] Axes

**Comment by MSWS** [comment]
Thank you for your suggestion.

I have added this enchantment in [v1.1.13](https://www.spigotmc.org/resources/64154/). If you have any more ideas feel free to create another issue.
