### ISSUE TITLE
A New enchantment

### ISSUE THREAD

**Issue by DarkerEnergon** [MSWS/FreakyEnchants#4]
**What is the name of the enchantment?**: Cleansing
_This should be short and generalize the enchantment_

**What is the max level for this enchantment?** 1-3
_What would each level effect [if anything]?_ The amount of healing it does 

**What does the enchantment do?** The enchantment allows the player to use their xP to heal by shifting for longer then 10 seconds or less (this does take away xP as a power soarce)
_Please be very descriptive. Include if this should have a cooldown or a certain duration, and if so then how that would be determined (eg: enchantment level)_

**What items can this enchantment be applied to (can select multiple)?**
- [ ] Swords
- [ ] Bows
- [* ] Armor
- [ ] Pickaxes 
- [ ] Axes

**Comment by MSWS** [comment]
Definitely an interesting idea. I will see what I can do, thanks for the suggestion!

**Comment by MSWS** [comment]
Enchantment has been created! Thank you for your suggestion.

[v1.2](https://www.spigotmc.org/resources/freakyenchants-gui-npc-support-1-8-1-12-2.64154/update?update=269615) now has the new enchantment.
